### ISSUE TITLE
`redraw` breaks primary render

### ISSUE THREAD

**Issue by mnichols** [isiahmeadows/mithril-helpers#1]
I tried using SelfSufficient and it somehow disrupts subsequent `render` calls on the top-level node.

I spun up a codepen here to demonstrate: https://codepen.io/nicholsmike/pen/pWjGoM?editors=1000.
Notice that clicking the button changes the vnode.attrs.model state but the DOM doesnt update until you move the mouse again (causing another redraw).

ref: https://github.com/MithrilJS/mithril.js/issues/1907

**Comment by dead-claudia** [comment]
Just pushed a fixed file. I added a helper method to help you out, as well as another lifecycle method to avoid related issues.

For event listeners, you'll want to use `onclick: this.link(vnode, handler)`, which basically is an explicit equivalent to what Mithril does implicitly with event handlers when you use `m.mount`.

**Comment by mnichols** [comment]
Thanks @isiahmeadows I'll have a look as soon as I can. Thanks for this!
