### ISSUE TITLE
Self-sufficient.js might have tiny spell error?

### ISSUE THREAD

**Issue by yedemon** [isiahmeadows/mithril-helpers#4]
Oh, dear isiahmeadows..

    I found self-sufficient just solves my problem. Therefore in line 75 of self-sufficient.js, cancelAnimationframe, is it to be cancelAnimationFrame? 

   By the way, about efficiency, I wondor how many SelfSufficient components should be used. For example, I'd like to create a list of ToolPanel. which varies in size(say about 50+). And each panel might have its toolsets which can also be complex. The whole thing is much the same as the toolpanels of photoshop. So, in this sinario, should i create SelfSufficient components for EACH toolpanel, Or just One SelfSufficient as root of the ToolPanels?

   My English is not good, so sorry for the inconvenience.

**Comment by dead-claudia** [comment]
Fixed the typo with `cancelAnimationFrame`: https://github.com/isiahmeadows/mithril-helpers/commit/4b799ba5fbb991a77ed8488e0770a09e1d8b2d4f

As for efficiency, I'd advise test it and see which one's quicker. In general, it depends on how commonly multiple child instances are updated as well as the list itself, but of course, you don't really know until you actually test it whether the tradeoff is worth it. I do want to note that the difference in overhead shouldn't be substantial.

**Comment by yedemon** [comment]
Oh i see.. Thanks again. I'll try to learn that.

= =b, how to close this issue? Clicked the "close issue and commit" but it still remains open.

**Comment by yedemon** [comment]
Well, there is no problem now..

**Comment by yedemon** [comment]
Oh i see.. Thanks again. I'll try to learn that.

**Comment by dead-claudia** [comment]
Closed for you. You may want to take a look at https//help.github.com - it can teach you all the ropes on how to use the site, including how to close issues. 🙂

**Comment by dead-claudia** [comment]
@yedemon BTW, I just pushed a new commit that optimized it substantially by removing a layer of indirection at the component layer and, if you're using the `.mjs` variant, moving to a set to reduce redraw scheduling overhead, so should you go the route of using 50 different roots, it should behave a little better. (You won't likely notice a substantial difference unless you're dealing with thousands of children, though.)

**Comment by yedemon** [comment]
That's very kind, thanks. I'll have a try!!
