### ISSUE TITLE
self-sufficient(Component) does not send remove to it's children. HELP~

### ISSUE THREAD

**Issue by yedemon** [isiahmeadows/mithril-helpers#5]
Hi`` isiahmeadows. 

I'm using self-sufficient to create independant components. Somehow I found my components were not receiving `onremove` hook calls. Here is the example.

[https://jsfiddle.net/1zfsp8jb/2/](url)

When I hit Close(R) button, I'm expecting "comp remove"->“my button remove”->"msf remove" . However, "my button remove"  never comes out. So... what should i do to get those hook calls, or am i getting wrong with the concept of mithril(and self-sufficient). Please help. Thanks. (I'm new to mithril and not very familiar.)

**Comment by dead-claudia** [comment]
Try it with the latest commit - should be fixed now.

**Comment by yedemon** [comment]
wow.. thanks，very much.. I will try it this afternoon.

**Comment by yedemon** [comment]
Oh.. but, i got error this time..

I update the demo with the newest code. but i got errors.. 
Uncaught Error: State is currently locked!"

[https://jsfiddle.net/mrknLaj9/1/](https://jsfiddle.net/mrknLaj9/1/)

Please. Help

**Comment by dead-claudia** [comment]
[Confirmed fixed now.](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4A9ACoJAHTQACCXICqcGHOKEIcdbTlbaUDIzkBPWgFcATnLpYADvRFywl2ljkBZCBugBybZYwACaWGADucnAmcIxYFJG6GrSqcmGEtLIKcuYpAAZY+IFoQTCWuXJBEIHUxFAmNhjyMdBQ2SlmVjZuDmgi+HIAksT+chhQcLo5MGDmrRDy3nCZirRh8pYQAOYkemCmFr6BbfObcvmFTCVlFVUwNXXxcPPUah0N8lPqmtrEGfKKACMjNRCPtOoEQuFtPMbJooEEuvZHAw4PFGgjvCMxhM2tNZs5aNYIPZYDgGCdlpFzADiIE1BDQmE4PhlmJZLIANwAChmaBqEHoch5GBqhJMAEo5MBMnJZdIQJ8YhsavL2fJZbshcQTHYYLQ9lhaEFZmoALzmuTy2gA3h3YjyuQAMkdckNxtgTpdbpN+BgAA8HJZiHBJdL1RqNd7YL6A4Tg3JTc4Rb9LCYuTKI5m5IEAI7mW7pkBYbyEDZQMRFK7y8UUDNZjW5-OBQvFjRliuXUpiABuaCNMGrdYj4rrrDkMHGaggey52t1+tdCYt8t5-Po1alQ41XIKhAnuss2gAPkehbv96VtIngKxxeL8ABlCdgB-mMCQagQJyJsDJsXp8N61lApK1KeICl7fst1lEdALHCcUjDIC21WORegiABRSxXEsQsvDbaBXRyYg5ABNQoFoDASgRSBD2IABCQc4NkW8eXMPliAFeQuVAyx4gANT7EpQzreVFVpCAVRANUI27DBrBcLgBiCeJ5hiJY0DrVdOMFeZu1oABrGAACVgkZLkRMA2T5MiEFghNBFEzU4MZPrZyr2cUIcGUhM0NmKBXKzMBCSFOSiV8gAGDk9DkAAeWy93dYJ8FgNBNg0aKIAAaiyyygIjMQxDkAB1NRemCUYSNgDAYgSHAk1mEjflgUI+TUABaPRhgRMjUhgKoMT2CYcEcaDM0K8dJxGUocO0OxAm7EQKscOQFwsawGShFkrPrMK9DQWrEzgOykqCZAIAAXTGiNnJS3zaXMAcdqzWl6iQ-Ks14gCPo+27mSCNxa2en7ZWQLkItUg7iHwZkjFpZluy-MJxS5ZzxQuoGQaA27LGu+tYJBsdqGBUEuRgPKsdlVRiAAFWJPVzGINiOK4oVQy+VwIjUdg5AigmfrHSBMCgOpN2B7Gobun9sSewmxtYUdAucdi1w+A6TpNVGoYprNpyFdylz8kXJUCYgrE04G9a19SUqYdLQXNRMAEYdfyq33OQCKLrkeiLTR7MYDNywLZB4m2qgABBNBiSMLiADEvJgHlE+U-nfqhjzFO8xyjYC4H4MnMWQb2+YSj9Xz3PwUv-QAeTAa3iDTt2Z2r8uAD5Ez5-abbgOwoEkpPW-iPn5cVkONW01mnygF83w-L8GC5SDhKL3abNUGf7u+MafGZDzl9l+td8KXzJ8FCypUiZ8LkhMIL4V4Hj9aRM0H8se62n2f30khfofm2hfhzhgPgRGMAIg-hVjpbiB9XYRmPvvISh9PqB3NnIA++A4aHkKLQAB79AKf1fN-T8fR-6AJ1MA+g1BAhGDNB-Z8hD54kNcGQ3U+B6DmDsEEGhp9IGsyXog2BGorZP0lChCI6E5BYRwoWB8xBuFaBsFYIotR6gUWoEZIIjEQBNwjOxY6iVNa7x0RqJ+91LCPR3qmVeH0vroIBnEOQYMIZoMQRg4g8MQFIxRkYjGXwtCFGMbKQW8wxii3eh9Ux0tJyj2YuPWUBC54-yYQAgB5C2FoECIaRaPCWbnxgdYzM8Ct7+OsC-N+j9vhS3UOYpBmY9Ea1gLOb4gSA7FFKPw-s+B7FNwfnWCaAAFak-dqByAjv0gYdCZ4MKSQwfApDUmsLgBgMAZpla5O4oI2UptUH0SfngiMCSiG-zmcwhZwDNrgLWarNmBSbozl2ZUqAmzMzuwzobV+xtbk-QNomZAu8rri3rFnGAPlEyNngMQKOMcoEJy4FrfSRlTK3xaRGAuiE8ZZj2pcCuGdbZpQ0HITqTsMXjSKhHKA1Cgj1CMF8NQlx4h9h8GlOQsAwBNV0ADbalNZSvPUsgS43tHZ+JDAHIOcSsYlzaeXJyuLW51yaVoWCJK7n6ylXIDuvNnkgwmgMeQxMUi71SKXbQHDIh2GwFgEw8QBjvF8E1DARlaVoQwAAe+yRgOw-8RSEC5dyiMaRoBqC1mXOK45ihau5R7Vugru7BnOmqrKcgnYAr9RLMuOVlX1gfqmoRGd+XFBjbvTNQTJrosBenG2dgciEAbiirNJLs31tiZMr+jDZnzKATfRkD4TB8hydci+4SXkziKRaD5TyOaoQkTTchUjCSFgAMKNDtQHW+ow2WlGyGgQ07FoZMWxiOx57z-KiNLFOsBcgZ26jnbheUS60ArouUapIjNRjZhwXu7RO9KnsM4TQhVe8elK22cHOQhy232jQLeNUshJAyH+HIAAAkAqUBQF3dGRLTchcBs0SDZHyegtUPAmAAEKM1+PIa8dZKHUOMEvZ5QgJjRgopsLkvhLWkXI4KKhMAaG+HFByUcmMNT0EybQbJ9GvmykYwYYBLG2McYBFx9YMAskwH44JuCwnZS-q4XR7sDHCOyZSrQVj7H6hKfcYKDhen1MCaE3WUBERJNDustYGI3DEzdjcR4jzjBNNARA-ILAbHLMUd8PEYAlDhkGUQDAU0bdgAyeY6ZsmAnIhyMYF28IFkOSsB5r4YjZGrNoC5EocU-Gx69LQHtOA6QwjofsGYx6mnZCMZIo1uwvkh30HmN4Qdwr8DUBixVKJKR2COaRh0lermGwoNAyF88UADzMnAzM4gkWSWuAAYgV0hZKjdmrPEElTndt+bNG3Rxxa9u+DC-QCLUpouSVi92BLwA6urE66aX8k4OQgTMjl8U+X4i+AXRRVQXJjIVZrNdkLRXlORfO4gc7t5tNYxC-KfAwUMiUEtCAYqhAaUKN3gAfiO5acthTKnDee8Ea7EYSd7cx0CSwWOMDQHlMd-HhB6iVARG8Gn6jXQwBJ-RMnX7KdAV2xjggLPOdSdTU99Ru2L4JcvsfQXGjmvczR36nm8oABSxE5AGQgEESoaUGUAM0My34V81B7kCPgZ3R2SUYxJaJ1T4mk4GYV0BZLcnUvsbgHsMTi0NMNvlj0tHnu1MubGgHkzZnbBdbD3ZgLGoH7VYKDuxeANqDmDJNDAERorVSlO69tuH2GvdBJyFzr4pEDjtvJpygIAN52i4ggHgTsAAcAAmRAEU2AcBAJgHAeAhtwAEDQegjBmA8DYBjEA-c0AGW76gMfXA8CtlLNANvVhyA8BIMQOwcBECFXYnYAymwhtuDELvssiH+-4AivgAALA-ksZZ8DFjQPgfgNvIBPAY6DYOwUQVgC6VgIAA)

**Edit:** [Relevant commit](https://github.com/isiahmeadows/mithril-helpers/commit/5d81f2dad08a91c97a7bb2e3a1ddfc53233d8139)

**Comment by yedemon** [comment]
Appreciate that.
