### ISSUE TITLE
self-sufficient.js line 120, inst?

### ISSUE THREAD

**Issue by yedemon** [isiahmeadows/mithril-helpers#6]
Hi, isiahmeadows.

Thank a lot for your last help, everything works fine, but today i came to this line. 

line 120.                    insts.push(inst)

there is no inst here. "Uncaught ReferenceError: inst is not defined"..

= =b.. Need help again. (I tried to replace with this.. but another error happens. )

It seems to occur when delete one component from a list of components with key, in which each component is a self-sufficient, and the whole list of components are inside another self-sufficient.

**Comment by dead-claudia** [comment]
Fixed: https://github.com/isiahmeadows/mithril-helpers/commit/721b466665f8d71dcee2e3ad1406a2eacfc8b9fe

**Comment by yedemon** [comment]
Thanks```
